name: License check

on:
  push:
    branches: [ "dev-dagshub" ]
  pull_request:
    branches: [ "dev-dagshub" ]

jobs:
  license-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: dagshub/node-license-checker-action@v1
      env:
        # pacakges which actually live inside this repo, in packages/*
        EXCLUDE_PACKAGES: '@fiftyone/create-plugin;@fiftyone/plugin-build;dagshub'
        NPM_INSTALL_CMD: npm install --ignore-scripts
          
    - uses: dagshub/node-license-checker-action@v1
      env:
        TARGET_DIR: packages/dagshub
        EXCLUDE_PACKAGES: 'dagshub'
        NPM_INSTALL_CMD: npm install --ignore-scripts
        
    - name: Unify license.csv files
      run: |
        commit="$GITHUB_SHA"
        base_link="github.com/$GITHUB_REPOSITORY"
        date=`date "+%B %e %Y"`
        awk -F',' -v "commit=$commit" -v "base_link=$base_link" -v "date=$date" '{OFS=","; print base_link,commit,date,$1,$2,$3}' licenses.csv >> node-licenses.csv

        pkg="packages/dagshub"
        awk -F',' -v "commit=$commit" -v "base_link=$base_link/tree/dev-dagshub/$pkg" -v "date=$date" '{OFS=","; print base_link,commit,date,$1,$2,$3}' $pkg/licenses.csv >> node-licenses.csv

    - name: Upload node license report
      uses: actions/upload-artifact@v3
      with:
        name: node-licenses.csv
        path: node-licenses.csv
        if-no-files-found: error
        
