name: License check

on:
  push:
    branches: [ "dev-dagshub" ]
  pull_request:
    branches: [ "dev-dagshub" ]

jobs:
  license-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      
    - uses: dagshub/node-license-checker-action@v1
      env:
        # pacakges which actually live inside this repo, in packages/*
        EXCLUDE_PACKAGES: '@fiftyone/create-plugin;@fiftyone/plugin-build;dagshub'
        NPM_INSTALL_CMD: npm install --ignore-scripts
          
    - uses: dagshub/node-license-checker-action@v1
      env:
        TARGET_DIR: packages/dagshub
        EXCLUDE_PACKAGES: 'dagshub'
        NPM_INSTALL_CMD: npm install --ignore-scripts
