name: License check

on:
  push:
    branches: [ "dev-dagshub" ]
  pull_request:
    branches: [ "dev-dagshub" ]

jobs:
  license-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3

    - name: Download node_modules
      run: yarn install
      
    - uses: dagshub/node-license-checker-action@v1
